# Generated by Django 5.0.2 on 2024-02-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=11)),
                ("dsg", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
            ],
        ),
    ]
